source "https://rubygems.org"

gem "rails", "4.2.1"
gem "pg"
gem "puma"
gem "sass-rails", "~> 5.0", ">= 5.0.1"
gem "uglifier", ">= 1.3.0"
gem "jbuilder", "~> 2.0"
gem "jquery-rails", ">= 4.0.3"
gem "devise", ">= 3.5.1"

group :development, :test do
  gem "byebug"
  gem "web-console", "~> 2.1", ">= 2.1.0"
end
