source "https://rubygems.org"

gem "rails", "4.2.0"
gem "pg"
gem "puma"
gem "sass-rails", "~> 5.0", ">= 5.0.0"
gem "uglifier", ">= 1.3.0"
gem "jbuilder", "~> 2.2", ">= 2.2.6"
gem "jquery-rails"
gem "devise"

group :development, :test do
  gem "byebug"
  gem "web-console", "~> 2.0", ">= 2.0.0"
end
