source "https://rubygems.org"

gem "rails", "5.2.6.2"
gem "pg"
gem "puma", ">= 4.3.11"
gem "sass-rails", "~> 5.0", ">= 5.0.5"
gem "uglifier", ">= 1.3.0"
gem "jbuilder", "~> 2.0"
gem "jquery-rails", ">= 4.0.2"
gem "devise", ">= 4.4.2"

group :development, :test do
  gem "byebug"
  gem "web-console", "~> 2.1", ">= 2.1.0"
end
